In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from scipy import stats
%matplotlib inline

In [3]:
df=pd.read_csv('Social_Network_Ads.csv',sep=',')

In [4]:
df.shape

(400, 5)

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
le=LabelEncoder()

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
User ID            400 non-null int64
Gender             400 non-null object
Age                400 non-null int64
EstimatedSalary    400 non-null int64
Purchased          400 non-null int64
dtypes: int64(4), object(1)
memory usage: 15.7+ KB


In [8]:
df.drop('User ID',axis=1,inplace=True)

In [9]:
df['Gender']=le.fit_transform(df['Gender'])

In [10]:
x=df.drop('Purchased',axis=1)

In [11]:
y=df['Purchased']

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.3)

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
sc=StandardScaler()

In [16]:
x_train_sc=sc.fit_transform(x_train)
x_test_sc=sc.transform(x_test)

In [17]:
from sklearn.naive_bayes import GaussianNB
gu=GaussianNB()

In [18]:
df.skew()

Gender             0.040159
Age                0.231337
EstimatedSalary    0.495024
Purchased          0.596903
dtype: float64

In [19]:
gu.fit(x_train_sc,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [20]:
y_pred=gu.predict(x_train_sc)

In [21]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [22]:
accuracy_score(y_train,y_pred)

0.8642857142857143

In [23]:
y_pred1=gu.predict(x_test_sc)

In [24]:
print(accuracy_score(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))
print(classification_report(y_test,y_pred1))

0.9083333333333333
[[71  2]
 [ 9 38]]
              precision    recall  f1-score   support

           0       0.89      0.97      0.93        73
           1       0.95      0.81      0.87        47

    accuracy                           0.91       120
   macro avg       0.92      0.89      0.90       120
weighted avg       0.91      0.91      0.91       120



In [25]:
from sklearn.naive_bayes import BernoulliNB

In [26]:
bu=BernoulliNB()

In [27]:
bu.fit(x_train_sc,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [28]:
y_pred2=bu.predict(x_train_sc)
print(accuracy_score(y_train,y_pred2))
y_pred3=bu.predict(x_test_sc)
print(accuracy_score(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3))
print(classification_report(y_test,y_pred3))

0.725
0.725
[[66  7]
 [26 21]]
              precision    recall  f1-score   support

           0       0.72      0.90      0.80        73
           1       0.75      0.45      0.56        47

    accuracy                           0.73       120
   macro avg       0.73      0.68      0.68       120
weighted avg       0.73      0.72      0.71       120



In [29]:
from sklearn.preprocessing import MinMaxScaler

In [30]:
mn=MinMaxScaler()

In [31]:
x_train_mn=mn.fit_transform(x_train)
x_test_mn=mn.transform(x_test)

In [32]:
from sklearn.naive_bayes import MultinomialNB
mu=MultinomialNB()

In [33]:
mu.fit(x_train_mn,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [34]:
y_pred5=mu.predict(x_train_mn)
print(accuracy_score(y_train,y_pred5))
y_pred6=mu.predict(x_test_mn)
print(accuracy_score(y_test,y_pred6))
print(confusion_matrix(y_test,y_pred6))
print(classification_report(y_test,y_pred6))

0.6571428571428571
0.6083333333333333
[[73  0]
 [47  0]]
              precision    recall  f1-score   support

           0       0.61      1.00      0.76        73
           1       0.00      0.00      0.00        47

    accuracy                           0.61       120
   macro avg       0.30      0.50      0.38       120
weighted avg       0.37      0.61      0.46       120

